### ISSUE TITLE
Feature may not be used in the beta release channel

### ISSUE THREAD

**Issue by geakstr** [bjz/glfw-rs#309]
I try to build glfw-rs with rustc 1.0.0-beta and getting

```
/Users/geakstr/.cargo/git/checkouts/glfw-rs-66a8b4b1793a8461/master/src/lib.rs:21:1: 21:18 error: unstable feature
/Users/geakstr/.cargo/git/checkouts/glfw-rs-66a8b4b1793a8461/master/src/lib.rs:21 #![feature(core)]
                                                                                  ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
/Users/geakstr/.cargo/git/checkouts/glfw-rs-66a8b4b1793a8461/master/src/lib.rs:22:1: 22:22 error: unstable feature
/Users/geakstr/.cargo/git/checkouts/glfw-rs-66a8b4b1793a8461/master/src/lib.rs:22 #![feature(std_misc)]
                                                                                  ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 2 previous errors
Could not compile `glfw`.
```

**Comment by irauta** [comment]
I did some digging. The #[feature(core)] line could be removed if instead of using as_ref on line 803 of lib.rs there was a manual null check. The std_misc one seems trickier, as it is caused by the use of std::rt::at_exit on line 412 of the same file. Using atexit from libc sounds bit ugly to me. (Also I'm not sure if it would work on the beta version as it lacks the stability annotation.)

**Comment by irauta** [comment]
I forked and made those two changes, see this commit: https://github.com/irauta/glfw-rs/commit/a021e9896eabb5b828b67260dc778aca9a66a26f

**Comment by daboross** [comment]
@irauta are you planning on submitting a PR for that, or?

**Comment by irauta** [comment]
Did that a moment ago, just hesitated because of the quick-and-dirty nature of the changes.
